### ISSUE TITLE
Possibility to toggle between current dark theme and light theme

### ISSUE THREAD

**Issue by jamofer** [webosbrew/pages#24]
People who have astigmatism or high-order aberrations can't properly read light text on a dark background.

I have high-order aberrations, and I can confirm that the website with the current color scheme is impossible to look at for more than a minute. It takes a big effort to read it.

**Comment by Dystopian** [comment]
@jamofer
I use https://addons.mozilla.org/ru/firefox/addon/togglewebsitecolors/ for Firefox, it helps me with about 90% of dark sites.

**Comment by jamofer** [comment]
Thank you very much! I don't know why I didn't try to search something like that before. It works perfectly!

**Comment by mariotaku** [comment]
Hi @jamofer , would you mind sharing the page after you apply the color fix? I'll consider adding styles to support `prefers-color-scheme`.

**Comment by jamofer** [comment]
Sure. After using the suggested addon I see the page like this:
![imagen](https://github.com/webosbrew/webosbrew.github.io/assets/9080627/0d613d1f-b3d1-4402-aed5-b5307805da6a)

All backgrounds change to white and font color to black.

And the following screenshot is after applying this css change:
```css
html {
  background-color:#fff;  /* <---- */
  color:#000;  /* <---- */
  font-family:helvetica neue,Helvetica,Arial,sans-serif
}

footer {
  color:#333;  /* <---- */
  font-size:small
}
```
![imagen](https://github.com/webosbrew/webosbrew.github.io/assets/9080627/1a515363-2aa5-4114-b0ac-5a5926e10e97)

I think it looks better than the first option with the Firefox addon and for me is good enough for reading with my condition.
